# Generated by Django 3.2.7 on 2022-11-13 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0007_alter_blood_donate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_donate',
            name='date',
            field=models.DateField(default=datetime.date(2022, 11, 13)),
        ),
    ]
